platform :ios,’8.0’
use_frameworks!

inhibit_all_warnings!

target ‘Keezy’ do
  pod 'SnapKit', '~> 0.15.0'
  #pod 'Reachability', '~> 3.2'
  #pod 'ASIHTTPRequest', '~> 1.8.2'
  #pod 'FMDB', '~> 2.4'
  #pod 'UMengSocialCOM', '~> 5.2.1'
  #pod 'UMengAnalytics-NO-IDFA', '~> 3.6.7'
  #pod 'LKbadgeView', '~> 1.1.0'
  #pod 'RegexKitLite', '~> 4.0'
  #pod 'MBProgressHUD', '~> 0.9'
  #pod 'DACircularProgress', '~> 2.2.0'
  #pod 'PSTCollectionView', '~> 1.2.3'
  #pod 'SDWebImage', '~> 3.7.1'
  #pod 'pop', '~> 1.0'
  #pod 'INSPullToRefresh', '~> 1.1'
  #pod 'BaiduMapKit', '~> 3.0.0'

  #pod 'JSONModel'
  #pod 'FXBlurView'
  #pod 'Masonry'
  #pod 'AFNetworking', '~> 2.5.4'
  #pod 'FDStackView', '>= 1.0-alpha'
  #pod 'FCUUID'
  #pod 'UIView+FDCollapsibleConstraints', '~> 1.1'
  #pod 'iCarousel', '~> 1.8.2'
  #pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
  #pod 'KVOController'
  #pod 'Bolts/Tasks'
  #pod 'Base64nl'
  #pod 'BLKit',  :path => "./libs/lib/BLKit/"
  #pod 'MarqueeLabel', '~> 2.7.1'
  #pod 'Tweaks'

  # pod 'dyci', :configuration => ["Debug"]
end

#target 'beiliaoTests' do
  #pod 'FBSnapshotTestCase/Core'
#end

#post_install do |installer|
#    puts("Update debug pod settings to speed up build time")
#    Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
#        puts "updating file: #{file}"
#        File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
#    end
#end
